  package:
    name: daspy
    version: 1.0.0
  
  source:
    git_url: https://github.com/HMZ-03/DASPy.git
   
  build:
    number: 0
  
  requirements:
    build:
      - python =3.10
      - setuptools
    run:
      - python =3.10
      - numpy
      - scipy >=1.13
      - matplotlib
      - geographiclib
      - pyproj
      - h5py
      - segyio
      - nptdms
  
  test:
    imports:
      - daspy
  
  about:
    home: https://github.com/HMZ-03/DASPy
    license: MIT
    summary: Python package for DAS (Distributed Acoustic Sensing) data processing
    description: Classic seismic data processing techniques and specialized algorithms for DAS applications.
    dev_url: https://github.com/HMZ-03/DASPy